### ISSUE TITLE
`GET /courses/:id/students` - Fetch a list of students enrolled in the Course

### ISSUE THREAD

**Issue by theusaf** [theusaf/osu-cs493-final-project#10]
## Description
Returns a list containing the User IDs of all students currently enrolled in the Course. Only an authenticated User with 'admin' role or an authenticated 'instructor' User whose ID matches the `instructorId` of the Course can fetch the list of enrolled students.

### Success (200)
```json
{
  "students": [
    {
      "name": "Jane Doe",
      "email": "doej@oregonstate.edu",
      "password": "hunter2",
      "role": "student"
    }
  ]
}
```

### Unauthorized (403)
```json
{
  "error": "string"
}
```

### Not Found (404)
```json
{
  "error": "string"
}
```

**Comment by JACKRUNDLE** [comment]
router.get("/:id/students", requireAuthentication, async (req, res) => {
  try {
    const courseId = req.params.id;
    const course = await Course.findById(courseId);

    if (!course) {
      return res.status(404).json({ error: "Course not found" });
    }

    const authUser = req.user;

    if (
      authUser.role !== "admin" &&
      (authUser.role !== "instructor" || authUser._id !== course.instructorId)
    ) {
      return res.status(403).json({ error: "Unauthorized" });
    }
    
    const students = course.studentIds;

    const studentsInClass = [];
    for (let i = 0; i < students.length; i++ ){
      const users = await User.findById(students[i]);
        var temp = { 
          name: users.name,
          email: users.email,
          role: users.role,
        };
        studentsInClass[i] = temp;
    }

    res.json({ students: studentsInClass });
  } catch (error) {
    console.error("Error fetching enrolled students:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});
